default_install_hook_types:
  - pre-commit
  - pre-push
repos:
- repo: local
  hooks:
  - id: check-types
    name: check types
    entry: uv run zuban check
    language: system
    types: [python]
    stages: ["commit"]
    require_serial: false
    always_run: true
  - id: check-format
    name: check format
    entry: uv run ruff format --check
    language: system
    types: [python]
    stages: ["commit"]
    require_serial: false
    always_run: true
  - id: lint
    name: lint
    entry: uv run ruff check
    language: system
    types: [python]
    stages: ["commit"]
    require_serial: false
    always_run: true
  - id: test
    name: test
    entry: uv run uvtask test
    language: system
    types: [python]
    stages: ["push"]
    require_serial: true
    always_run: true
