default_install_hook_types:
  - pre-commit
  - pre-push
repos:
- repo: local
  hooks:
  - id: check-homeassistant-current
    name: check Home Assistant is current
    entry: scripts/check_homeassistant_current.sh
    language: system
    stages: ["pre-commit"]
    require_serial: true
    always_run: true
    pass_filenames: false

  - id: check-quality
    name: check code quality
    entry: uv run poe check
    language: system
    types: [python]
    stages: ["pre-commit"]
    require_serial: false
    always_run: true

  - id: test
    name: run unit tests
    entry: uv run poe test
    language: system
    types: [python]
    stages: ["pre-push"]
    require_serial: true
    always_run: true
