default_install_hook_types:
  - pre-commit
  - pre-push
repos:
- repo: local
  hooks:
  - id: check
    name: check
    entry: uv run task check
    language: system
    types: [python]
    stages: ["commit"]
    require_serial: true
    always_run: true
  - id: test
    name: test
    entry: uv run task test
    language: system
    types: [python]
    stages: ["push"]
    require_serial: true
    always_run: true
