#!/usr/bin/env bash

set -e

op=$1
if [[ -z $op ]]; then
	op=help
fi

case $op in
	init)
		pip3 install pipenv
		pipenv install --dev
		pipenv run pre-commit install
		;;
	
	test)
		pipenv run mypy custom_components/hubitat
		pipenv run python -m pytest
		;;

	help)
		echo "$0 COMMAND"
		echo
		echo "Commands:"
		echo "  init - initialize for development"
		echo "  publish - build and publish to PyPi"
		echo "  test - run type checker and unit tests"
		echo
esac
