#!/usr/bin/env bash

set -e

op=$1
if [[ -z $op ]]; then
	op=help
fi

if ! hash poetry 2> /dev/null; then
	echo "Please install poetry"
	echo "See https://python-poetry.org/docs/#installation"
	exit 1
fi

case $op in
	init)
		poetry install
		poetry run pre-commit install
		;;
	
	test)
		poetry run mypy custom_components/hubitat
		poetry run python -m pytest
		;;

	help)
		echo "$0 COMMAND"
		echo
		echo "Commands:"
		echo "  init - initialize for development"
		echo "  publish - build and publish to PyPi"
		echo "  test - run type checker and unit tests"
		echo
esac
