DEVICE_CLASS_DOOR: str
DEVICE_CLASS_GARAGE_DOOR: str
DEVICE_CLASS_GAS: str
DEVICE_CLASS_MOISTURE: str
DEVICE_CLASS_MOTION: str
DEVICE_CLASS_MOVING: str
DEVICE_CLASS_PRESENCE: str
DEVICE_CLASS_SMOKE: str
DEVICE_CLASS_WINDOW: str

class BinarySensorEntity: ...
