from abc import ABC
from typing import Any, Optional

from homeassistant.helpers.entity_registry import RegistryEntry

class Entity(ABC):
    entity_id: str
    registry_entry: Optional[RegistryEntry] = None
    @property
    def device_class(self) -> Optional[str]: ...
    def async_schedule_update_ha_state(self, force_refresh: bool = False) -> None: ...

class ToggleEntity(Entity):
    state: str
    @property
    def is_on(self) -> bool: ...
    async def async_turn_on(self, **kwargs: Any) -> None: ...
    async def async_turn_off(self, **kwargs: Any) -> None: ...
    async def async_toggle(self, **kwargs: Any) -> None: ...
