from homeassistant.backports.enum import StrEnum


class DeviceCapability(StrEnum):
    ALARM = "Alarm"
    CARBON_DIOXIDE = "CarbonDioxideMeasurement"
    CARBON_MONOXIDE = "CarbonMonoxideDetector"
    COLOR_CONTROL = "ColorControl"
    COLOR_MODE = "ColorMode"
    COLOR_TEMP = "ColorTemperature"
    CONTACT_SENSOR = "ContactSensor"
    DOOR_CONTROL = "DoorControl"
    ENERGY_METER = "EnergyMeter"
    ENERGY_SOURCE = "EnergySource"
    GARAGE_DOOR_CONTROL = "GarageDoorControl"
    HOLDABLE_BUTTON = "HoldableButton"
    ILLUMINANCE_MEASUREMENT = "IlluminanceMeasurement"
    LIGHT = "Light"
    LOCK = "Lock"
    LOCK_CODES = "LockCodes"
    MOTION_SENSOR = "MotionSensor"
    MUSIC_PLAYER = "MusicPlayer"
    POWER_METER = "PowerMeter"
    POWER_SOURCE = "PowerSource"
    PRESENCE_SENSOR = "PresenceSensor"
    PRESSURE_MEASUREMENT = "PressureMeasurement"
    PUSHABLE_BUTTON = "PushableButton"
    DOUBLE_TAPABLE_BUTTON = "DoubleTapableButton"
    RELATIVE_HUMIDITY_MEASUREMENT = "RelativeHumidityMeasurement"
    SECURITY_KEYPAD = "SecurityKeypad"
    SWITCH = "Switch"
    SWITCH_LEVEL = "SwitchLevel"
    TEMPERATURE_MEASUREMENT = "TemperatureMeasurement"
    THERMOSTAT = "Thermostat"
    WINDOW_SHADE = "WindowShade"
    FAN_CONTROL = "FanControl"


class DeviceAttribute(StrEnum):
    ACCELERATION = "acceleration"
    ALARM = "alarm"
    BATTERY = "battery"
    CARBON_DIOXIDE = "carbonDioxide"
    CARBON_MONOXIDE = "carbonMonoxide"
    CODE_CHANGED = "codeChanged"
    CODE_LENGTH = "codeLength"
    COLOR_MODE = "colorMode"
    COLOR_NAME = "colorName"
    COLOR_TEMP = "colorTemperature"
    CURRENT = "current"
    CONTACT = "contact"
    DOOR = "door"
    DOUBLE_TAPPED = "doubleTapped"
    ENERGY = "energy"
    ENERGY_SOURCE = "energySource"
    ENTRY_DELAY = "entryDelay"
    EXIT_DELAY = "exitDelay"
    HELD = "held"
    HUE = "hue"
    HUMIDITY = "humidity"
    ILLUMINANCE = "illuminance"
    LAST_CODE_NAME = "lastCodeName"
    LEVEL = "level"
    LOCK = "lock"
    LOCK_CODES = "lockCodes"
    MAX_CODES = "maxCodes"
    MOTION = "motion"
    NAME = "name"
    NUM_BUTTONS = "numberOfButtons"
    POSITION = "position"
    POWER = "power"
    PRESENCE = "presence"
    PRESSURE = "pressure"
    POWER_SOURCE = "powerSource"
    PUSHED = "pushed"
    SATURATION = "saturation"
    SECURITY_KEYPAD = "securityKeypad"
    SMOKE = "smoke"
    TEMPERATURE = "temperature"
    UV = "ultravioletIndex"
    VOLTAGE = "voltage"
    WATER = "water"
    WINDOW_SHADE = "windowShade"
    SPEED = "speed"
    SWITCH = "switch"


class DeviceCommand(StrEnum):
    ARM_AWAY = "armAway"
    ARM_HOME = "armHome"
    ARM_NIGHT = "armNight"
    AUTO = "auto"
    AWAY = "away"
    BOTH = "both"
    CLOSE = "close"
    COOL = "cool"
    DELETE_CODE = "deleteCode"
    DISARM = "disarm"
    ECO = "eco"
    EMERGENCY_HEAT = "emergencyHeat"
    FAN_AUTO = "fanAuto"
    FAN_CIRCULATE = "fanCirculate"
    FAN_ON = "fanOn"
    FLASH = "flash"
    GET_CODES = "getCodes"
    HEAT = "heat"
    LOCK = "lock"
    OFF = "off"
    ON = "on"
    OPEN = "open"
    PRESENT = "present"
    SET_CODE = "setCode"
    SET_CODE_LENGTH = "setCodeLength"
    SET_COLOR = "setColor"
    SET_COLOR_TEMP = "setColorTemperature"
    SET_ENTRY_DELAY = "setEntryDelay"
    SET_EXIT_DELAY = "setExitDelay"
    SET_HUE = "setHue"
    SET_LEVEL = "setLevel"
    SET_POSITION = "setPosition"
    SET_SAT = "setSaturation"
    SET_HEATING_SETPOINT = "setHeatingSetpoint"
    SET_COOLING_SETPOINT = "setCoolingSetpoint"
    SET_PRESENCE = "setPresence"
    SET_THERMOSTAT_MODE = "setThermostatMode"
    SET_FAN_MODE = "setThermostatFanMode"
    SIREN = "siren"
    STROBE = "strobe"
    UNLOCK = "unlock"
    SET_SPEED = "setSpeed"
    CYCLE_SPEED = "cycleSpeed"


# See https://docs.hubitat.com/index.php?title=Hubitat®_Safety_Monitor_Interface
class HsmCommand(StrEnum):
    ARM_ALL = "armAll"
    ARM_AWAY = "armAway"
    ARM_HOME = "armHome"
    ARM_NIGHT = "armNight"
    ARM_RULES = "armRules"
    CANCEL_ALERTS = "cancelAlerts"
    DISARM = "disarm"
    DISARM_ALL = "disarmAll"
    DISARM_RULES = "disarmRules"


class HsmStatus(StrEnum):
    ARMED_AWAY = "armedAway"
    ARMING_AWAY = "armingAway"
    ARMED_HOME = "armedHome"
    ARMING_HOME = "armingHome"
    ARMED_NIGHT = "armedNight"
    ARMING_NIGHT = "armingNight"
    DISARMED = "disarmed"
    ALL_DISARMED = "allDisarmed"


class DeviceState(StrEnum):
    ARMED_AWAY = "armed away"
    ARMED_HOME = "armed home"
    ARMED_NIGHT = "armed night"
    CLOSED = "closed"
    CLOSING = "closing"
    DISARMED = "disarmed"
    LOCKED = "locked"
    LOW = "low"
    OFF = "off"
    ON = "on"
    OPEN = "open"
    OPENING = "opening"
    PARTIALLY_OPEN = "partially open"
    UNKNOWN = "unknown"
    UNLOCKED = "unlocked"
    UNLOCKED_WITH_TIMEOUT = "unlocked with timeout"


class ColorMode(StrEnum):
    RGB = "RGB"
    CT = "CT"


ID_MODE = "hub_mode"
ID_HSM_STATUS = "hub_hsm_status"

DEFAULT_FAN_SPEEDS = [
    "low",
    "medium-low",
    "medium",
    "medium-high",
    "high",
    "on",
    "off",
    "auto",
]
