name: Issue Created

on:
  issues:
    types: [opened]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jason0x43/action-project-manager@v0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project: Development
          column: To do
